#!/usr/bin/env python2
# coding: utf-8

__author__ = 'ch4n3'

import requests
import json

headers = {
    'Authorization': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMzY4LCJ1c2VybmFtZSI6ImNoYW5leW9vbiIsImVtYWlsIjoiY2hhbmV5b29uQGdtYWlsLmNvbSIsIm5hbWUiOiLsnKTshJ3ssKwiLCJuaWNrIjoiPCEtLSIsImdlbmRlciI6Ik0iLCJ1c2VyX3R5cGUiOiJTIiwiYmlydGhkYXRlIjoiMjAwMS0wMi0yMCIsInBob25lIjpudWxsLCJzdGF0dXMiOjEwLCJwaG90b2ZpbGUxIjoicGhvdG8xXzAwMTM2OF9jaGFuZXlvb25fM0FLbDJGLmpwZyIsInBob3RvZmlsZTIiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDE3LTAzLTAyIDE1OjQzOjA0IiwidXBkYXRlZF9hdCI6IjIwMTctMDctMTIgMTU6MzE6NDgiLCJwYXNzd29yZF9oYXNoIjpudWxsLCJzc29fdG9rZW4iOiJMN21QRklOSlZjNjF3cHQlMkZkWDBGdmdMQTZkMDViNWtBTG12eHR5cVk0MUhReE1ubzl4WDhzNDVKZWFSU0NlY00ifSwic3R1ZGVudCI6eyJpZCI6NDA5LCJ1c2VyX2lkIjoxMzY4LCJ1c2VybmFtZSI6ImNoYW5leW9vbiIsIm5hbWUiOiLsnKTshJ3ssKwiLCJnZW5kZXIiOiJNIiwicGhvbmUiOm51bGwsImdyYWRlIjoyLCJjbGFzcyI6NiwibnVtYmVyIjoyMywic2VyaWFsIjoiMjYyMyIsInJmY2FyZF91aWQiOiI2MEM2NzNBMDUwMDEwNEUwIiwicGhvdG9maWxlMSI6InBob3RvMV8wMDEzNjhfY2hhbmV5b29uXzNBS2wyRi5qcGciLCJwaG90b2ZpbGUyIjpudWxsLCJkb3JtaXRvcnkiOiLtlZnrtInqtIAiLCJyb29tX251bSI6IjMyMCIsImJpcnRoZGF0ZSI6IjIwMDEtMDItMjAiLCJlbWFpbCI6ImNoYW5leW9vbkBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOm51bGwsInVwZGF0ZWRBdCI6bnVsbH0sIm1hbmdlciI6ZmFsc2UsInZlciI6MiwiaWF0IjoxNTM2MzI3ODg1LCJleHAiOjE1Mzg5MTk4ODV9.qAZTu5V6IIonN9WcNLZ0w1usOjD0eMjC-t4Se2jvmqI'
}
def getStayLists():
    r = requests.get('http://api.dimigo.life/service/stay', headers=headers)
    dump = json.loads(r.text)
    return dump

print getStayLists()
